name: 'Autopick'
description: 'Automatically creates a cherry pick PR'
inputs:
  githubToken:
    description: 'API token automatically injected by Github'
    required: true
  targetVersion:
    description: 'Target version to cherry-pick to'
    required: true
  prNumber:
    description: 'PR to cherry-pick'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
