name: Automatic cherry pick

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull request number to cherry-pick'
        required: true
      version:
        description: 'Target version to cherry pick (e.g. 5.75.0)'
        required: true
jobs:
  autopick:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${GITHUB_REF##*/}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch everything so we can mess around with branches
      - name: yarn
        working-directory: ./.github/actions/autopick
        run: yarn
      - name: Prepare git configs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
      - name: Create cherry pick PR
        uses: ./.github/actions/autopick
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetVersion: ${{ github.event.inputs.version }}
          prNumber: ${{ github.event.inputs.pull_request_number }}
