name: Comment triggers

on:
  issue_comment:
    types: [created]

jobs:
  automate:
    # Only trigger on comments that start with slash "/"
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn
        working-directory: ./.github/actions
        run: yarn
      - name: Comment triggers
        uses: ./.github/actions/comment-triggers
        env:
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          githubToken: ${{ secrets.PAT_TEST }}
